model:
  base_learning_rate: 4.5e-6
  target: taming.models.cond_transformer.Net2NetTransformer
  params:
    unconditional: True
    cond_stage_key: image
    transformer_config:
      target: taming.modules.transformer.mingpt.GPT
      params:
        vocab_size: 16384
        block_size: 512
        n_layer: 24
        n_head: 16
        n_embd: 1024
    first_stage_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: logs/2021-10-26T08-15-54_wikiart_f16_16384/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 16384
        ddconfig:
          double_z: False
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1,1,2,2,4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [16]
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
    cond_stage_config:
      target: taming.models.dummy_cond_stage.DummyCondStage
      params:
        dummyparam: False

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 14
    num_workers: 16
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: /home/ginxian_kok/datasets/wikiart_train.txt
        size: 256
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: /home/ginxian_kok/datasets/wikiart_test.txt
        size: 256

